import matplotlib.pyplot as plt 
plt.plot([2,5], [1,1], color='darkmagenta', marker='.', ms=10)
plt.plot([2,2], [1,5], color='violet', marker='.', ms=10)
plt.plot([5,5], [5,1], color='violet', marker='.', ms=10)
plt.plot([2,5], [5,5], color='indigo', marker='.', ms=10)
plt.plot([2,3], [1,2], color='m', marker='.', ms=10,linestyle='--',linewidth=1)
plt.plot([5,6], [1,2], color='m', marker='.', ms=10,)
plt.plot([3,6], [2,2], color='darkmagenta', marker='.', ms=10,linestyle='--',linewidth=1)
plt.plot([6,6], [2,5.5], color='b', marker='.', ms=10,)
plt.plot([5,6], [5,5.5], color='k', marker='.', ms=10,)
plt.plot([2,3], [5,5.5], color='k', marker='.', ms=10,)
plt.plot([3,6], [5.5,5.5], color='indigo', marker='.', ms=10,)
plt.plot([3,3], [2,5.5], color='b', marker='.', ms=10, linestyle='--',linewidth=1)
plt.axis('equal')
plt.xlabel('x')
plt.ylabel('y')
plt.title('cube')
plt.show()

